### ISSUE TITLE
whatsapp works with google chrome 60+

### ISSUE THREAD

**Issue by changwuf31** [flathub/io.bit3.WhatsAppQT#1]
I got this errors a few times already.
What is the chrome version used on the flatpak version ?

Thank you :+1:

**Comment by felipe-heredia** [comment]
@changwuf31  Press F5 and WhatsappQT will work again.

**Comment by changwuf31** [comment]
@felipesuri thank you, will try F5 when I encounter this issue again :+1:

**Comment by changwuf31** [comment]
Encounter a few times again, and F5 does work,

Thank you :+1:

**Comment by lfortes** [comment]
Thanks
