### ISSUE TITLE
Multiple Instances shouldnt be possible

### ISSUE THREAD

**Issue by thomhoess** [flathub/io.bit3.WhatsAppQT#2]
Once WhatsAppQT is opened and then closed it runs in the background and has a tray icon. - fine!

Opening WhatsAppQT from the App Menu again doesn't bring the window back in the foreground but opens an additional instance of the program. This also creates an additional tray icon. This could be repeated as often as you want.

IMO only one single instance of the application should be allowed to run at the same time.

Expected behaviour: It should check if an instance of the app is running and if it does should bring the window of the running app back in front.

**Comment by tristanlins** [comment]
Please open app related issues in the [gitlab tracker](https://gitlab.com/bit3/whatsappqt/-/issues).
This repository is only related to the flathub manifest.
